In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os
os.getcwd()


'/content'

In [ ]:
!ls

drive  sample_data


In [ ]:
#this is the dataset location which is shown in video
'''
os.chdir('/content/drive/My Drive/ANN')
'''
#now you have to use below one as you already created Data folder shortcut in My Drive
os.chdir('/content/drive/My Drive/Data')


In [ ]:
os.getcwd()

'/content/drive/My Drive/ANN'

In [ ]:
!ls

In [ ]:
import pandas as pd
dataset = pd.read_csv("Churn_Modelling.csv")

In [ ]:
dataset.shape


(10000, 14)

In [ ]:
dataset['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [ ]:
dataset.shape

In [ ]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
features = dataset.iloc[:, 3:13].values
labels = dataset.iloc[:, 13].values

In [ ]:
type(features)

numpy.ndarray

In [ ]:
features.shape

(10000, 10)

In [ ]:
features[0:10,:]

In [ ]:
dataset.dtypes

In [ ]:
features


In [ ]:
labels

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1,2])], remainder='passthrough')

features = np.array(columnTransformer.fit_transform(features), dtype = np.float32)



In [ ]:
features[0:10,:]


array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 6.1900000e+02, 4.2000000e+01, 2.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 6.0800000e+02, 4.1000000e+01, 1.0000000e+00,
        8.3807859e+04, 1.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 5.0200000e+02, 4.2000000e+01, 8.0000000e+00,
        1.5966080e+05, 3.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.1393157e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 6.9900000e+02, 3.9000000e+01, 1.0000000e+00,
        0.0000000e+00, 2.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        9.3826633e+04],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        0.0000000e+0

In [ ]:

features = features[:, 1:] #drop the first dummy column for Geography


In [ ]:
features[0]

array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0134888e+05], dtype=float32)

In [ ]:

features = features[:, [0,1,3,4,5,6,7,8,9,10,11]] #drop the column for Gender


In [ ]:
features.shape

(10000, 11)

In [ ]:
features[0,:]

In [ ]:
features.shape

In [ ]:
from sklearn.model_selection import train_test_split
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size = 0.2, random_state = 0)

In [ ]:
features[0]

array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       4.2000000e+01, 2.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0134888e+05], dtype=float32)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
features_train = sc.fit_transform(features_train)
features_test = sc.transform(features_test)

In [ ]:
features_train[0]

array([-0.56984437,  1.7430905 , -1.0916871 ,  0.16958177, -0.46460798,
        0.00666099, -1.2157176 ,  0.8095029 ,  0.64259493, -1.0322704 ,
        1.1064317 ], dtype=float32)

In [ ]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
classifier = Sequential()

In [ ]:
features.shape

In [ ]:
#adding the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [ ]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation='sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
classifier.fit(features_train, labels_train, batch_size = 10, epochs = 10)

Epoch 1/10
800/800 [==============================] - 2s 2ms/step - loss: 0.4822 - accuracy: 0.7959
Epoch 2/10
800/800 [==============================] - 2s 2ms/step - loss: 0.4263 - accuracy: 0.7960
Epoch 3/10
800/800 [==============================] - 2s 2ms/step - loss: 0.4207 - accuracy: 0.8106
Epoch 4/10
800/800 [==============================] - 2s 2ms/step - loss: 0.4169 - accuracy: 0.8251
Epoch 5/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4155 - accuracy: 0.8285
Epoch 6/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4136 - accuracy: 0.8304
Epoch 7/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4127 - accuracy: 0.8321
Epoch 8/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4113 - accuracy: 0.8331
Epoch 9/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4104 - accuracy: 0.8345
Epoch 10/10
800/800 [==============================] - 1s 2ms/step - loss: 0.4088 - accuracy: 0.8315

In [ ]:
labels_pred = classifier.predict_classes(features_test)
#labels_pred = (labels_pred > 0.5)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [ ]:
labels_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [ ]:
len(labels_pred)

2000

In [ ]:
list(zip(labels_test, labels_pred))

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, labels_pred)

In [ ]:
cm


array([[1563,   32],
       [ 290,  115]])